Repository RevenueCat/react-native-purchases, pull requests merged in 2022-08, with the labels that each got.

#409 Release/5.0.0-beta.6
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#416 Release/5.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#418 Specify branch for deployment dependencies
  .circleci/config.yml
Labels: ci

#417 Prepare next version: 5.1.0-SNAPSHOT
  .version
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#421 Configures Danger
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: ci

#425 `presentCodeRedemptionSheet`: fixed Catalyst build
  ios/RNPurchases.m
Labels: fix

#422 Release train
  .circleci/config.yml
  Gemfile.lock
  RELEASING.md
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#427 Release/5.0.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RNPurchases.podspec
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#426 Add link to reference docs at the bottom
  README.md
Labels: docs
