Repository RevenueCat/react-native-purchases, pull requests merged in 2023-01, with the labels that each got.

#509 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#512 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#513 Adds missing params for better changelogs when bumping
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#517 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#522 Adds PurchasesStoreProduct.susbcriptionPeriod
  apitesters/offerings.ts
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
  scripts/setupJest.js
  src/offerings.ts
Labels: feat

#526 `DEVELOPMENT.md`: replaced `yarn` commands with `npx`
  DEVELOPMENT.md
Labels: docs

#525 Fixed `Xcode` spelling
  DEVELOPMENT.md
Labels: docs

#527 `DEVELOPMENT.md`: clarified invocation commands
  DEVELOPMENT.md
Labels: docs

#523 Add beginRefundRequest APIs for iOS 15+
  __tests__/index.test.js
  apitesters/enums.ts
  apitesters/purchases.ts
  ios/RNPurchases.m
  scripts/setupJest.js
  src/errors.ts
  src/purchases.ts
Labels: feat

#524 Add latest error codes from native layer to react native
  apitesters/errors.ts
  src/errors.ts
Labels: feat

#528 Adds missing docs for PurchasesConfiguration
  src/purchases.ts
Labels: docs

#534 Change prepublish hook to prepare
  package.json
Labels: build
