Repository RevenueCat/react-native-purchases, pull requests merged in 2023-06, with the labels that each got.

#641 Add offering metadata
  RNPurchases.podspec
  android/build.gradle
  apitesters/offerings.ts
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
  scripts/setupJest.js
  src/offerings.ts
Labels: feat

#644 Release/6.0.0-rc.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#653 Release/6.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#657 [DENG-418] Accept `GoogleProductChangeInfo` in `purchasePackage` in Android
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
Labels: fix

#661 Fix V6 migration docs to use correct method name
  migrations/v6-MIGRATION.md
Labels: docs
