Repository RevenueCat/react-native-purchases, pull requests merged in 2023-04, with the labels that each got.

#598 Update CircleCI Xcode version to 14.3.0
  .circleci/config.yml
  examples/purchaseTesterTypescript/.ruby-version
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/package.json
Labels: ci

#601 Create v4_to_v5_migration_guide.md
  README.md
  v4_to_v5_migration_guide.md
Labels: docs

#610 Update `react-native-reanimated` in MagicWeather example app
  examples/MagicWeather/package.json
Labels: test

#617 Release/5.13.4
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#616 Release/6.0.0-alpha.1
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#621 Release/6.0.0-beta.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  fastlane/Fastfile
  ios/RNPurchases.m
  package.json
  scripts/docs/index.html
Labels: next_release

#622 Update fastlane-plugin-revenuecat version
  Gemfile.lock
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  fastlane/Fastfile
Labels: ci
