Repository RevenueCat/react-native-purchases, pull requests merged in 2023-02, with the labels that each got.

#540 Update gems
  Gemfile.lock
Labels: dependencies

#541 Configures dependabot
  .github/dependabot.yml
  Gemfile
Labels: dependencies

#531 Added `setLogLevel`
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/purchases.ts
  examples/MagicWeather/App.js
  examples/purchaseTesterTypescript/App.tsx
  ios/RNPurchases.m
  scripts/setupJest.js
  src/purchases.ts
Labels: feat

#545 Upgrade purchase tester to React Native 0.71.2
  .circleci/config.yml
  .gitignore
  examples/purchaseTesterTypescript/.buckconfig
  examples/purchaseTesterTypescript/.bundle/config
  examples/purchaseTesterTypescript/.editorconfig
  examples/purchaseTesterTypescript/.gitattributes
  examples/purchaseTesterTypescript/.gitignore
  examples/purchaseTesterTypescript/.node-version
  examples/purchaseTesterTypescript/.prettierrc.js
  examples/purchaseTesterTypescript/.ruby-version
  examples/purchaseTesterTypescript/Gemfile
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/android/app/_BUCK
  examples/purchaseTesterTypescript/android/app/build.gradle
  examples/purchaseTesterTypescript/android/app/build_defs.bzl
  examples/purchaseTesterTypescript/android/app/src/debug/AndroidManifest.xml
  examples/purchaseTesterTypescript/android/app/src/debug/java/com/revenuecat/purchases_sample/ReactNativeFlipper.java
  examples/purchaseTesterTypescript/android/app/src/main/AndroidManifest.xml
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.java
  examples/purchaseTesterTypescript/android/app/src/main/res/drawable/rn_edit_text_material.xml
  examples/purchaseTesterTypescript/android/app/src/main/res/values/styles.xml
  examples/purchaseTesterTypescript/android/app/src/release/java/com/purchases_sample/ReactNativeFlipper.java
  examples/purchaseTesterTypescript/android/build.gradle
  examples/purchaseTesterTypescript/android/gradle.properties
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.jar
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.properties
  examples/purchaseTesterTypescript/android/gradlew
  examples/purchaseTesterTypescript/android/settings.gradle
  examples/purchaseTesterTypescript/babel.config.js
  examples/purchaseTesterTypescript/ios/.xcode.env
  examples/purchaseTesterTypescript/ios/Dummy.swift
  examples/purchaseTesterTypescript/ios/Podfile
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.h
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.m
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.mm
  examples/purchaseTesterTypescript/ios/PurchaseTester/Images.xcassets/AppIcon.appiconset/Contents.json
  examples/purchaseTesterTypescript/ios/PurchaseTester/Info.plist
  examples/purchaseTesterTypescript/ios/PurchaseTester/main.m
  examples/purchaseTesterTypescript/ios/PurchaseTesterTests/PurchaseTesterTests.m
  examples/purchaseTesterTypescript/ios/PurchasesExample-Bridging-Header.h
  examples/purchaseTesterTypescript/metro.config.js
  examples/purchaseTesterTypescript/package.json
  examples/purchaseTesterTypescript/react-native.config.js
  examples/purchaseTesterTypescript/tsconfig.json
  package.json
  src/customerInfo.ts
  src/offerings.ts
Labels: test

#546 Changes to npm scripts and DEVELOPMENT.md
  DEVELOPMENT.md
  examples/MagicWeather/package.json
  examples/purchaseTesterTypescript/package.json
  package.json
Labels: build

#553 Reformats files
  .editorconfig
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesPackage.java
  apitesters/enums.ts
  apitesters/errors.ts
  apitesters/purchases.ts
  src/purchases.ts
Labels: style
