Repository RevenueCat/react-native-purchases, pull requests merged in 2023-11, with the labels that each got.

#764 Fix purchaseSubscriptionOption not accepting oldProductIdentifier
  android/src/main/java/com/revenuecat/purchases/react/GoogleUpgradeInfo.java
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
Labels: fix

#773 release/4.6.3
  .circleci/config.yml
  CHANGELOG.latest.md
  CHANGELOG.md
  RNPurchases.podspec
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  examples/purchaseTester/ios/Podfile.lock
  examples/purchaseTester/ios/ReactNativeSample.xcodeproj/project.pbxproj
  examples/purchaseTesterTypescript/android/build.gradle
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.jar
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.properties
  examples/purchaseTesterTypescript/android/gradlew
  examples/purchaseTesterTypescript/ios/Podfile.lock
  ios/RNPurchases.m
  package.json
Labels: next_release

#774 Update `VERSIONS` with `4.6.3`
  VERSIONS.md
Labels: docs

#782 `CI`: disable `prepare-next-version`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#678 `Trusted Entitlements`: add support for setting `EntitlementVerificationMode`
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/App.tsx
  ios/RNPurchases.m
  src/purchases.ts
Labels: feat
