Repository RevenueCat/react-native-purchases, pull requests merged in 2024-03, with the labels that each got.

#927 Upgrade jest to fix yargs-parser to fix vulnerabilities
  .yarnrc.yml
  examples/purchaseTesterTypescript/package.json
  package.json
  react-native-purchases-ui/package.json
  yarn.lock
Labels: test

#928 Increase react-native dev dependency version
  package.json
  react-native-purchases-ui/package.json
  yarn.lock
Labels: build

#929 Update react native version in purchase tester
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .npmrc.SAMPLE
  .nvmrc
  examples/purchaseTesterTypescript/.eslintrc.js
  examples/purchaseTesterTypescript/.gitignore
  examples/purchaseTesterTypescript/.node-version
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/__tests__/App-test.tsx
  examples/purchaseTesterTypescript/android/app/build.gradle
  examples/purchaseTesterTypescript/android/app/src/debug/AndroidManifest.xml
  examples/purchaseTesterTypescript/android/app/src/debug/java/com/revenuecat/purchases_sample/ReactNativeFlipper.java
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainActivity.java
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainActivity.kt
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.java
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.kt
  examples/purchaseTesterTypescript/android/app/src/main/res/drawable/rn_edit_text_material.xml
  examples/purchaseTesterTypescript/android/app/src/release/java/com/purchases_sample/ReactNativeFlipper.java
  examples/purchaseTesterTypescript/android/build.gradle
  examples/purchaseTesterTypescript/android/gradle.properties
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.jar
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.properties
  examples/purchaseTesterTypescript/android/gradlew
  examples/purchaseTesterTypescript/android/gradlew.bat
  examples/purchaseTesterTypescript/android/settings.gradle
  examples/purchaseTesterTypescript/babel.config.js
  examples/purchaseTesterTypescript/ios/Podfile
  examples/purchaseTesterTypescript/ios/Podfile.lock
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.mm
  examples/purchaseTesterTypescript/ios/PurchaseTester/Info.plist
  examples/purchaseTesterTypescript/metro.config.js
  examples/purchaseTesterTypescript/package.json
  examples/purchaseTesterTypescript/tsconfig.json
  package.json
  react-native-purchases-ui/package.json
  yarn.lock
Labels: build

#935 Add 6.7.2 to changelog
  CHANGELOG.md
  VERSIONS.md
Labels: docs

#936 Update RELEASING.md
  RELEASING.md
Labels: docs

#925 Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/offerings.ts
  apitesters/paywalls.tsx
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  examples/purchaseTesterTypescript/app/components/InputModal.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/ios/Podfile.lock
  ios/RNPurchases.m
  react-native-purchases-ui/package.json
  scripts/setupJest.js
  src/purchases.ts
  yarn.lock
Labels: feat

#942 Add trigger_bump lane
  Gemfile.lock
  fastlane/.env.SAMPLE
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#943 Fix `generate_docs`
  fastlane/Fastfile
Labels: ci

#945 Update changelog to include behavior change
  CHANGELOG.latest.md
  CHANGELOG.md
Labels: docs

#946 Update Podfile.lock when upgrading phc
  fastlane/Fastfile
Labels: ci

#950 Remove flipper from tester
  examples/purchaseTesterTypescript/android/app/build.gradle
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.kt
  examples/purchaseTesterTypescript/ios/Podfile
  examples/purchaseTesterTypescript/ios/Podfile.lock
Labels: test

#957 Fix issue with iOS purchaseProduct arguments
  ios/RNPurchases.m
Labels: fix

#954 Fix pod install of sample when updating phc
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#961 Remove usage of RCTEventEmitter in Android
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEventName.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/ViewExtensions.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnDismissEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseCancelledEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseCompletedEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseErrorEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnPurchaseStartedEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreCompletedEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreErrorEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/OnRestoreStartedEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/events/PaywallEvent.kt
Labels: refactor

#948 Add font support to presentPaywall
  apitesters/paywalls.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/FontAssetManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/src/index.tsx
Labels: feat
