Repository RevenueCat/react-native-purchases, pull requests merged in 2024-07, with the labels that each got.

#1032 Setting `proxyURL` should not require configure
  __tests__/index.test.js
  src/purchases.ts
Labels: fix

#1035 [EXTERNAL] Make the setProxyURL a promise to wait for the native code to set the proxy URL (#1033) contributed by @dangilbert
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  ios/RNPurchases.m
  src/purchases.ts
Labels: fix

#1043 Fix ws affected by a DoS
  examples/purchaseTesterTypescript/package.json
  yarn.lock
Labels: dependencies

#1049 Consume PHC 12.0.0
  RNPurchases.podspec
  __tests__/index.test.js
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/ios/Podfile.lock
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  ios/RNPurchases.m
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  src/purchases.ts
  yarn.lock
Labels: breaking, feat
