Repository RevenueCat/react-native-purchases, pull requests merged in 2024-02, with the labels that each got.

#889 Upgrade purchase tester dependencies to upgrade JSON5
  examples/purchaseTesterTypescript/package.json
  yarn.lock
Labels: dependencies, test

#892 Bump PHC 6.3.1
  RNPurchases.podspec
  android/build.gradle
  package.json
Labels: dependencies

#899 Update CHANGELOG to include 6.7.1 release notes
  CHANGELOG.md
  VERSIONS.md
Labels: refactor

#887 Add listener functions to views
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEvent.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPurchasesConverters.kt
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.h
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/src/index.tsx
Labels: feat

#906 Update cocoapods in Gemfile
  examples/purchaseTesterTypescript/Gemfile
  examples/purchaseTesterTypescript/Gemfile.lock
Labels: build

#911 Add `onPurchaseStarted` event
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEvent.kt
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.h
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/src/index.tsx
Labels: feat

#916 [EXTERNAL] Adding fontFamily from RN to CustomFontProvider in PaywallView (contributed by @Jjastiny)
  apitesters/paywalls.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/FontAssetManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/src/index.tsx
Labels: feat

#917 Add `fontFamily` usage to purchase tester
  examples/purchaseTesterTypescript/android/app/src/main/assets/fonts/Ubuntu.ttf
  examples/purchaseTesterTypescript/android/app/src/main/assets/fonts/Ubuntu_bold.ttf
  examples/purchaseTesterTypescript/android/app/src/main/assets/fonts/Ubuntu_bold_italic.ttf
  examples/purchaseTesterTypescript/android/app/src/main/assets/fonts/Ubuntu_italic.ttf
  examples/purchaseTesterTypescript/android/link-assets-manifest.json
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  examples/purchaseTesterTypescript/assets/fonts/Ubuntu.ttf
  examples/purchaseTesterTypescript/assets/fonts/Ubuntu_bold.ttf
  examples/purchaseTesterTypescript/assets/fonts/Ubuntu_bold_italic.ttf
  examples/purchaseTesterTypescript/assets/fonts/Ubuntu_italic.ttf
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  examples/purchaseTesterTypescript/ios/PurchaseTester/Info.plist
  examples/purchaseTesterTypescript/ios/link-assets-manifest.json
  examples/purchaseTesterTypescript/react-native.config.js
Labels: test

#918 Fix iOS caches
  .circleci/config.yml
  examples/purchaseTesterTypescript/.gitignore
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/ios/Podfile.lock
Labels: ci

#907 Add `onRestoreStarted`
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallEvent.kt
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.h
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/src/index.tsx
Labels: feat

#921 Add some logs on sizing of the PaywallViewWrapper
  react-native-purchases-ui/ios/PaywallViewWrapper.m
Labels: refactor
