Repository RevenueCat/react-native-purchases, pull requests merged in 2024-04, with the labels that each got.

#953 Add TVOS support for Expo apps
  RNPurchases.podspec
  ios/RNPurchases.m
  package.json
  yarn.lock
Labels: feat

#971 Use ReactContext instead of ThemedReactContext in PaywallFooterViewManager
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
Labels: fix

#972 Only update docs index on latest stable releases
  Gemfile.lock
  fastlane/Fastfile
Labels: ci
