Repository RevenueCat/react-native-purchases, pull requests merged in 2024-01, with the labels that each got.

#818 Release 7.15.0-rc.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RNPurchases.podspec
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  fastlane/Fastfile
  fastlane/README.md
  ios/RNPurchases.m
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  scripts/docs/index.html
  yarn.lock
Labels: RevenueCatUI

#822 RevenueCatUI: FooterView and full screen paywall fixes
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
Labels: RevenueCatUI

#828 Add paywalls api tests
  .circleci/config.yml
  apitesters/paywalls.ts
Labels: RevenueCatUI

#820 Add RNPaywall
  .editorconfig
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  examples/purchaseTesterTypescript/app/screens/CustomerInfoScreen.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/Paywall.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewShadowNode.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsPackage.kt
  react-native-purchases-ui/ios/PaywallViewManager.h
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/src/index.tsx
Labels: RevenueCatUI

#830 Add result present paywall
  RNPurchases.podspec
  apitesters/paywalls.ts
  examples/purchaseTesterTypescript/android/build.gradle
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/package.json
  react-native-purchases-ui/src/index.tsx
  yarn.lock
Labels: RevenueCatUI

#831 Creates RevenueCatUI class with static functions
  apitesters/paywalls.ts
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/src/index.tsx
Labels: RevenueCatUI

#835 Update PHC and fastlane plugin
  Gemfile.lock
  RNPurchases.podspec
  android/build.gradle
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  yarn.lock
Labels: dependencies, RevenueCatUI

#834 `PaywallFooterViewManager`: added controller to UIVC hierarchy
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/ios/UIView+Extensions.h
  react-native-purchases-ui/ios/UIView+Extensions.m
  react-native-purchases-ui/src/index.tsx
Labels: RevenueCatUI

#799 Add PaywallFooter support
  RNPurchases.podspec
  android/build.gradle
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsPackage.kt
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.h
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/ios/RNPaywalls.h
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/ios/UIView+Extensions.h
  react-native-purchases-ui/ios/UIView+Extensions.m
  react-native-purchases-ui/package.json
  react-native-purchases-ui/src/index.tsx
  yarn.lock
Labels: feat

#836 Made presentPaywallIfNeeded accept an object
  apitesters/paywalls.ts
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  react-native-purchases-ui/src/index.tsx
Labels: RevenueCatUI

#838 Release/7.15.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  fastlane/Fastfile
  ios/RNPurchases.m
  package.json
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  scripts/docs/index.html
  yarn.lock
Labels: next_release

#843 Use parameter instead of multiple commands to install yarn dependencies
  .circleci/config.yml
Labels: ci

#842 Add `displayCloseButton` parameters to functions
  apitesters/paywalls.ts
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/components/CustomerInfoHeader.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/src/index.tsx
Labels: feat, RevenueCatUI

#848 `Fastlane`: fix `bump_phc_version`
  fastlane/Fastfile
Labels: ci

#859 Add repositories to `purchaseTesterTypescript` android build.gradle
  examples/purchaseTesterTypescript/android/build.gradle
Labels: build

#858 `Paywalls`: separate `PurchasesHybridCommonUI`
  RNPurchases.podspec
  android/build.gradle
  examples/purchaseTesterTypescript/ios/Podfile
  fastlane/Fastfile
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/ios/RNPaywalls.h
  yarn.lock
Labels: RevenueCatUI

#861 `Paywalls`: extracted `PaywallViewWrapper`
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.h
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/ios/UIView+Extensions.h
  react-native-purchases-ui/ios/UIView+Extensions.m
Labels: refactor

#860 `PaywallViewManager`: added controller to UIVC hierarchy
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.h
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/ios/UIView+Extensions.h
  react-native-purchases-ui/ios/UIView+Extensions.m
Labels: fix

#855 Add Offering option to paywall functions
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/src/index.tsx
Labels: feat, RevenueCatUI

#864 `RNPaywalls.podspec`: remove `PurchasesHybridCommon` dependency
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RNPaywalls.h
  react-native-purchases-ui/ios/RNPaywalls.m
Labels: build

#865 Fix `update-hybrid-common-versions`
  .circleci/config.yml
Labels: ci

#867 Fix for footer in lansdcape mode in iOS
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
Labels: fix, RevenueCatUI

#874 Update react native devDependency versions
  __tests__/index.test.js
  babel.config.js
  package.json
  yarn.lock
Labels: build

#872 `purchasePackage`: add `StoreTransaction` in `MakePurchaseResult`
  __tests__/index.test.js
  scripts/setupJest.js
Labels: refactor

#850 Add `offering` option to paywall views
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
  examples/purchaseTesterTypescript/app/screens/PaywallScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/ios/PaywallViewManager.m
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RCPaywallFooterViewManager.m
  react-native-purchases-ui/src/index.tsx
Labels: feat, RevenueCatUI

#882 Remove 'new NativeEventEmitter() was called with a non-null argument'
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
Labels: fix

#883 Throw error if null module
  react-native-purchases-ui/src/index.tsx
Labels: fix

#875 Add xcodeproj to react-native-purchases-ui
  ios/RNPurchases.xcodeproj/project.pbxproj
  react-native-purchases-ui/ios/RNPaywalls.xcodeproj/project.pbxproj
  react-native-purchases-ui/package.json
Labels: fix
