Repository RevenueCat/react-native-purchases, pull requests merged in 2024-08, with the labels that each got.

#1054 replace syncObserverModeAmazonPurchase with syncAmazonPurchase
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  src/purchases.ts
Labels: fix

#1050 v8.0 Release
  RNPurchases.podspec
  __tests__/index.test.js
  android/build.gradle
  android/gradle.properties
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/attributes.ts
  apitesters/offerings.ts
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/ios/Podfile.lock
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  ios/RNPurchases.m
  migrations/v8-MIGRATION.md
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  scripts/setupJest.js
  src/purchases.ts
  yarn.lock
Labels: breaking, feat

#1063 Updates purchases-hybrid-common to 13.0.1
  RNPurchases.podspec
  android/build.gradle
  examples/purchaseTesterTypescript/ios/Podfile.lock
  fastlane/Fastfile
  package.json
  react-native-purchases-ui/RNPaywalls.podspec
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  yarn.lock
Labels: phc_dependencies

#1071 Typo fix in v8-MIGRATION.md
  migrations/v8-MIGRATION.md
Labels: docs

#1068 Refine StoreKitVersion logging in configure function
  src/purchases.ts
Labels: enhancement, fix

#1045 Adds pricePerPeriod functions to PurchasesStoreProduct
  apitesters/offerings.ts
  examples/purchaseTesterTypescript/app/screens/OfferingDetailScreen.tsx
Labels: feat
