Repository RevenueCat/react-native-purchases, pull requests merged in 2024-09, with the labels that each got.

#1084 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#1086 Update allowSharingAppStoreAccount deprecation message
  src/purchases.ts
Labels: pr:docs

#1091 Bump fastlane-plugin-revenuecat_internal from 5140dbc to 55a0455
  Gemfile.lock
Labels: pr:other
