Repository RevenueCat/react-native-purchases, pull requests merged in 2025-09, with the labels that each got.

#1383 Fix `react-native-purchases-ui` preview mode
  examples/purchaseTesterExpo/app/(tabs)/index.tsx
  react-native-purchases-ui/src/index.tsx
  react-native-purchases-ui/src/preview/previewComponents.tsx
Labels: pr:fix

#1371 Passing the PresentedOfferingContext from the Offering to the PHC APIs when navigating to a paywall
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallFooterViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPurchasesConverters.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/WrappedPaywallComposeView.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/WrappedPaywallFooterComposeView.kt
  react-native-purchases-ui/ios/PaywallViewWrapper.m
  react-native-purchases-ui/ios/RNPaywalls.m
  react-native-purchases-ui/src/index.tsx
Labels: pr:other, pr:RevenueCatUI

#1353 Support simulated store in Expo Go
  __tests__/alertHelper.test.ts
  __tests__/offeringsLoader.test.ts
  __tests__/purchaseSimulatedPackageHelper.test.ts
  src/browser/nativeModule.ts
  src/browser/simulatedstore/alertHelper.ts
  src/browser/simulatedstore/offeringsLoader.ts
  src/browser/simulatedstore/purchaseSimulatedPackageHelper.ts
Labels: pr:other

#1408 Implement log handler
  src/browser/nativeModule.ts
Labels: pr:feat

#1422 [V8] [CI] `bump` pipeline action won't trigger `deploy` workflow
  .circleci/config.yml
Labels: pr:other

#1424 [V8] Pass current version to determine next version action
  fastlane/Fastfile
Labels: pr:other

#1431 Add APITests for UI
  .circleci/config.yml
  react-native-purchases-ui/apitesters/customer_center.tsx
  react-native-purchases-ui/apitesters/paywalls.tsx
  react-native-purchases-ui/apitesters/tsconfig.json
  react-native-purchases-ui/package.json
  react-native-purchases-ui/tsconfig.json
Labels: pr:other, pr:RevenueCatUI
