Repository RevenueCat/react-native-purchases, pull requests merged in 2025-07, with the labels that each got.

#1309 Update workflows/issue-notifications.yml@v2
  .github/workflows/issue-notifications.yml
Labels: pr:other

#1295 Uses `mapAsync()` where possible to avoid ANRs.
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
Labels: pr:other

#1328 Fix blank `PaywallView` when using `react-navigation/stack`
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/WrappedPaywallComposeView.kt
  react-native-purchases-ui/src/index.tsx
Labels: pr:fix

#1307 Add web target and expo test app
  .circleci/config.yml
  .gitignore
  examples/purchaseTesterExpo/.gitignore
  examples/purchaseTesterExpo/.yarnrc.yml
  examples/purchaseTesterExpo/app.json
  examples/purchaseTesterExpo/app/(tabs)/_layout.tsx
  examples/purchaseTesterExpo/app/(tabs)/index.tsx
  examples/purchaseTesterExpo/app/(tabs)/two.tsx
  examples/purchaseTesterExpo/app/+html.tsx
  examples/purchaseTesterExpo/app/+not-found.tsx
  examples/purchaseTesterExpo/app/_layout.tsx
  examples/purchaseTesterExpo/app/modal.tsx
  examples/purchaseTesterExpo/assets/fonts/SpaceMono-Regular.ttf
  examples/purchaseTesterExpo/assets/images/adaptive-icon.png
  examples/purchaseTesterExpo/assets/images/favicon.png
  examples/purchaseTesterExpo/assets/images/icon.png
  examples/purchaseTesterExpo/assets/images/splash-icon.png
  examples/purchaseTesterExpo/babel.config.js
  examples/purchaseTesterExpo/components/EditScreenInfo.tsx
  examples/purchaseTesterExpo/components/ExternalLink.tsx
  examples/purchaseTesterExpo/components/StyledText.tsx
  examples/purchaseTesterExpo/components/Themed.tsx
  examples/purchaseTesterExpo/components/useClientOnlyValue.ts
  examples/purchaseTesterExpo/components/useClientOnlyValue.web.ts
  examples/purchaseTesterExpo/components/useColorScheme.ts
  examples/purchaseTesterExpo/components/useColorScheme.web.ts
  examples/purchaseTesterExpo/constants/APIKeys.ts
  examples/purchaseTesterExpo/constants/Colors.ts
  examples/purchaseTesterExpo/package.json
  examples/purchaseTesterExpo/tsconfig.json
  examples/purchaseTesterTypescript/Gemfile
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/ios/Podfile.lock
  package.json
  react-native-purchases-ui/package.json
  react-native-purchases-ui/src/__tests__/index.test.tsx
  react-native-purchases-ui/src/index.tsx
  react-native-purchases-ui/src/preview/previewComponents.tsx
  react-native-purchases-ui/src/utils/environment.ts
  src/preview/nativeModule.ts
  src/utils/environment.ts
  yarn.lock
Labels: pr:feat

#1334 Release/9.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  README.md
  VERSIONS.md
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  examples/purchaseTesterTypescript/ios/Podfile.lock
  ios/RNPurchases.m
  package.json
  react-native-purchases-ui/android/build.gradle
  react-native-purchases-ui/package.json
  scripts/docs/index.html
  yarn.lock
Labels: pr:next_release

#1336 Support Virtual Currencies
  __tests__/index.test.js
  android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/App.tsx
  examples/purchaseTesterTypescript/app/RootStackParamList.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  examples/purchaseTesterTypescript/app/screens/VirtualCurrencyScreen.tsx
  ios/RNPurchases.m
  scripts/setupJest.js
  src/preview/nativeModule.ts
  src/purchases.ts
Labels: pr:feat

#1340 getVirtualCurrencies() JSDoc Typo Fix
  src/purchases.ts
Labels: pr:other
