Repository RevenueCat/react-native-purchases, pull requests merged in 2025-04, with the labels that each got.

#1229 Virtual Currency Balances
  __tests__/index.test.js
  apitesters/customerInfo.ts
  apitesters/virtualCurrencyInfo.ts
  examples/purchaseTesterTypescript/app/screens/CustomerInfoScreen.tsx
  scripts/setupJest.js
Labels: pr:feat

#1240 Update Example app to RN v0.79
  examples/MagicWeather/App.tsx
  examples/MagicWeather/Gemfile
  examples/MagicWeather/README.md
  examples/MagicWeather/android/gradle/wrapper/gradle-wrapper.jar
  examples/MagicWeather/android/gradle/wrapper/gradle-wrapper.properties
  examples/MagicWeather/android/gradlew
  examples/MagicWeather/ios/MagicWeatherReactNative.xcodeproj/project.pbxproj
  examples/MagicWeather/ios/MagicWeatherReactNative/AppDelegate.swift
  examples/MagicWeather/package.json
Labels: pr:other

#1249 [EXTERNAL] Correctly sets RevenueCatUI podspec platform to `13.0` to fix compatibility issue (#1246) via @rgomezp
  react-native-purchases-ui/RNPaywalls.podspec
Labels: pr:fix, pr:RevenueCatUI
