Repository RevenueCat/react-native-purchases, pull requests merged in 2025-06, with the labels that each got.

#1275 Better native modules check for Preview API mode in react-native-purchases-ui
  react-native-purchases-ui/src/utils/environment.ts
Labels: pr:other

#1286 Posts request layout in `ComposeViewWrapper`
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/views/ComposeViewWrapper.kt
Labels: pr:fix, pr:RevenueCatUI

#1284 chore: update react-native-purchase-ui documentation
  README.md
  react-native-purchases-ui/README.md
Labels: pr:other

#1301 Force `presentPaywall` to run on main thread
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
Labels: pr:fix
