Repository RevenueCat/react-native-purchases, pull requests merged in 2025-02, with the labels that each got.

#1172 [Paywalls V2] Deprecate PaywallFooterContainerView in favor of OriginalTemplatePaywallFooterContainerView
  apitesters/paywalls.tsx
  examples/purchaseTesterTypescript/app/screens/FooterPaywallScreen.tsx
  react-native-purchases-ui/src/index.tsx
Labels: pr:other, pr:RevenueCatUI

#1195 Add missing 8.5.2 changelog
  CHANGELOG.md
Labels: pr:other

#1187 CustomerCenter Android
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNCustomerCenterModule.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RevenueCatUIPackage.kt
Labels: pr:feat

#1184 feat: Introduce CustomerCenter
  apitesters/customer_center.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/PaywallViewManager.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNCustomerCenterModule.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNPaywallsModule.kt
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RevenueCatUIPackage.kt
  react-native-purchases-ui/ios/RNCustomerCenter.h
  react-native-purchases-ui/ios/RNCustomerCenter.m
  react-native-purchases-ui/src/index.tsx
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#1193 Update purchase tester to 0.78.0
  .circleci/config.yml
  examples/purchaseTesterTypescript/.gitignore
  examples/purchaseTesterTypescript/.ruby-version
  examples/purchaseTesterTypescript/Gemfile
  examples/purchaseTesterTypescript/Gemfile.lock
  examples/purchaseTesterTypescript/android/app/build.gradle
  examples/purchaseTesterTypescript/android/app/src/main/AndroidManifest.xml
  examples/purchaseTesterTypescript/android/app/src/main/java/com/revenuecat/purchases_sample/MainApplication.kt
  examples/purchaseTesterTypescript/android/build.gradle
  examples/purchaseTesterTypescript/android/gradle.properties
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.jar
  examples/purchaseTesterTypescript/android/gradle/wrapper/gradle-wrapper.properties
  examples/purchaseTesterTypescript/android/gradlew
  examples/purchaseTesterTypescript/android/gradlew.bat
  examples/purchaseTesterTypescript/android/settings.gradle
  examples/purchaseTesterTypescript/ios/Podfile
  examples/purchaseTesterTypescript/ios/Podfile.lock
  examples/purchaseTesterTypescript/ios/PrivacyInfo.xcprivacy
  examples/purchaseTesterTypescript/ios/PurchaseTester.xcodeproj/project.pbxproj
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.h
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.mm
  examples/purchaseTesterTypescript/ios/PurchaseTester/AppDelegate.swift
  examples/purchaseTesterTypescript/ios/PurchaseTester/Info.plist
  examples/purchaseTesterTypescript/ios/PurchaseTester/main.m
  examples/purchaseTesterTypescript/ios/PurchaseTesterTests/Info.plist
  examples/purchaseTesterTypescript/ios/PurchaseTesterTests/PurchaseTesterTests.m
  examples/purchaseTesterTypescript/metro.config.js
  examples/purchaseTesterTypescript/package.json
  yarn.lock
Labels: pr:other

#1196 Workaround to remove `NSNull` objects in ObjC layer
  ios/RNPurchases.m
Labels: pr:fix
