Repository RevenueCat/react-native-purchases, pull requests merged in 2025-03, with the labels that each got.

#1203 [EXTERNAL] feat(ios): showManageSubscriptions (#1200) by @dylancom
  apitesters/purchases.ts
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  ios/RNPurchases.m
  src/purchases.ts
Labels: pr:feat

#1214 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#1216 Fix get products in iOS
  ios/RNPurchases.m
Labels: pr:fix

#1211 Add `callbacks` to `presentCustomerCenter`
  apitesters/customer_center.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/RNCustomerCenterModule.kt
  react-native-purchases-ui/ios/RNCustomerCenter.m
  react-native-purchases-ui/src/index.tsx
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#1220 Fix Typescript definition of onManagementOptionSelected
  apitesters/customer_center.tsx
  examples/purchaseTesterTypescript/app/screens/HomeScreen.tsx
  react-native-purchases-ui/src/index.tsx
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#1225 Fix crash on Paywalls when setting options with null offering
  react-native-purchases-ui/android/src/main/java/com/revenuecat/purchases/react/ui/BasePaywallViewManager.kt
Labels: pr:fix, pr:RevenueCatUI
